site_name: 'Debt Support Centre'
site_name_separator: '|'
basics:
  - basic
  - advanced
dublin_core:
  - dublin_core
  - dublin_core_advanced
google:
  - google_plus
  - google_cse
facebook:
  - og
  - facebook
social:
  - twitter
other:
  - favicons
